### PR TITLE
Some usage description for the metadata-team space

### PR DESCRIPTION
**Pull request by mbaudis**

### CODE REVIEW

**Comment by mbaudis** [comment]
O.k. I've started the agenda (https://docs.google.com/document/d/1zv0rzVL1_y2GZdJpss_j0sdr6ibFbSXgacOmYThNqAM/edit#heading=h.5s8093srwln5 <https://docs.google.com/document/d/1zv0rzVL1_y2GZdJpss_j0sdr6ibFbSXgacOmYThNqAM/edit#heading=h.5s8093srwln5>).

Hope to attend the DWG call, but backup would be good.

Best,

Michael.

**Comment by mbaudis** [comment]
There is this new publication with probable relevance for ontology record def. and G2P etc. Questions probably best to Suzy (or/and Marc R-R, who isn't involved with GA4GH but very helpful & responsive ...).

Best,

Michael.

> http://database.oxfordjournals.org/content/2015/bav043.full <http://database.oxfordjournals.org/content/2015/bav043.full>

**Comment by diekhans** [comment]
Nicole Washington <NLWashington@lbl.gov> is co-chair of G2P and
extremely knowledgeable about ontology, G2P, and software
engineering.  She works for Suzi and would be a good person to
loop in.

**Comment by mbaudis** [comment]
I know. Sorry; this went to the (rather limited distribution) github metadata-team address ...

Btw.: Mark, could you comment on the time attribute NULL note, please? Other thread, but I would like to merge, to go on with my life ...

Michael.

**Comment by helenp** [comment]
Hi

so 2 questions and a comment

1. how is this different from ECO?
2. is it intended to be used in conjunction with ECO?
3. Our experience with users is that they prefer to see the type of 
evidence - e.g. GWAS, KO etc - as well as the aggregation of these.

cheers

Helen


On 11/05/2015 21:37, Michael Baudis wrote:
> There is this new publication with probable relevance for ontology 
> record def. and G2P etc. Questions probably best to Suzy (or/and Marc 
> R-R, who isn't involved with GA4GH but very helpful & responsive ...).
>
> Best,
>
> Michael.
>
> > http://database.oxfordjournals.org/content/2015/bav043.full 
> <http://database.oxfordjournals.org/content/2015/bav043.full>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ga4gh/metadata-team/pull/1#issuecomment-101040645>.
>

-- 
Helen Parkinson, PhD
Team Leader
Samples, Phenotypes and Ontologies Team
-------------------------------------------
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom

EBI 01223 494672
For scheduling assistance please contact Lynn French lfrench@ebi.ac.uk, 01223 494 453
Skype: helen.parkinson.ebi
http://www.ebi.ac.uk/about/people/helen-parkinson

**Pull request merged**
